### ISSUE TITLE
issues with changing location

### ISSUE THREAD

**Issue by introvert** [nneal/tinder_pyro#5]
Hello,

I'm having some difficulties with changing location: everytime I try to set location with gps coordinates I get 200 successful response, but API won't change the location (even when I turn off the app on the phone with location services).

Any ideas what could it be?

Thanks

**Comment by nneal** [comment]
I'm wondering if, potentially, we need to spoof User Agent headers to get this to work... could be worth a shot

**Comment by matixmatix** [comment]
It works for me. It just needs some time time to settle in (it took around 0.5h for a 1000KM jump). Tinder detects when you "jumped" a lot in a short amount of time and then you get a "message"=>"recs timeout" from response. I checked this with @introvert and it works for him too. This can be closed IMO.

**Comment by nneal** [comment]
Thanks @matixmatix !
